// app/(tabs)/coach/plan.tsx
import { useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet,
  Alert, ActivityIndicator,
} from 'react-native';
import { useRouter, useLocalSearchParams, type Href } from 'expo-router';
import { supabase } from '../../../lib/supabase';
import { useAuthStore } from '../../../stores/authStore';
import { colors, typography, spacing } from '../../../constants/theme';
import type { PlanData, DayPlan } from '../../../types/database';

function parsePlan(raw: string): PlanData | null {
  try {
    return JSON.parse(raw) as PlanData;
  } catch {
    const match = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (match) {
      try { return JSON.parse(match[1]) as PlanData; } catch { /* fall through */ }
    }
    return null;
  }
}

function DayCard({ day }: { day: DayPlan }) {
  return (
    <View style={styles.dayCard}>
      <Text style={styles.dayLabel}>{day.day_label}</Text>
      {(day.exercises ?? []).map((ex, i) => (
        <View key={i} style={styles.exRow}>
          <Text style={styles.exName}>{ex.exercise_name}</Text>
          <Text style={styles.exMeta}>{ex.sets} × {ex.reps_low}–{ex.reps_high}</Text>
        </View>
      ))}
    </View>
  );
}

export default function PlanScreen() {
  const router = useRouter();
  const { plan: planRaw, source } = useLocalSearchParams<{ plan: string; source?: string }>();
  const userId = useAuthStore(s => s.session?.user.id);
  const profile = useAuthStore(s => s.profile);
  const [saving, setSaving] = useState(false);

  const planData = planRaw ? parsePlan(planRaw) : null;

  const handleSave = async () => {
    if (!planData || !userId || !profile) return;
    setSaving(true);
    try {
      await supabase
        .from('workout_plans')
        .update({ is_active: false })
        .eq('user_id', userId);

      const { error } = await supabase.from('workout_plans').insert({
        user_id: userId,
        split_type: source === 'algorithm' ? 'algorithm' : 'custom',
        days_per_week: profile.workout_days?.length ?? planData.days.length,
        plan_data: planData,
        is_active: true,
        generated_by: source === 'algorithm' ? 'algorithm' : 'claude',
      });
      if (error) throw error;

      router.replace('/(tabs)/workout');
    } catch (e: unknown) {
      Alert.alert('Error', e instanceof Error ? e.message : 'Could not save plan');
    } finally {
      setSaving(false);
    }
  };

  if (!planData) {
    return (
      <View style={styles.centered}>
        <Text style={styles.errorText}>
          Could not read the plan. Try regenerating.
        </Text>
        <TouchableOpacity
          style={styles.btn}
          onPress={() => router.replace('/(tabs)/coach/generate' as Href)}
        >
          <Text style={styles.btnText}>Regenerate</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <ScrollView style={styles.scroll} contentContainerStyle={styles.container}>
      <TouchableOpacity onPress={() => router.back()} style={styles.back}>
        <Text style={styles.backText}>← Back</Text>
      </TouchableOpacity>

      <Text style={styles.heading}>Your Personalized Plan</Text>
      <Text style={styles.sub}>Generated by Coach Mayari 🌙</Text>

      {planData.days.map((day) => <DayCard key={day.day_label} day={day} />)}

      <TouchableOpacity
        style={[styles.btn, saving && styles.btnOff]}
        onPress={handleSave}
        disabled={saving}
      >
        {saving
          ? <ActivityIndicator color="#fff" />
          : <Text style={styles.btnText}>Save This Plan</Text>}
      </TouchableOpacity>

      <TouchableOpacity
        style={styles.regenBtn}
        onPress={() => router.replace('/(tabs)/coach/generate' as Href)}
        disabled={saving}
      >
        <Text style={styles.regenBtnText}>Regenerate</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: colors.bg.primary },
  container: { padding: spacing.lg, paddingBottom: spacing['2xl'] },
  centered: {
    flex: 1,
    backgroundColor: colors.bg.primary,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  back: { marginBottom: spacing.md },
  backText: { color: colors.brand.primary, fontSize: typography.base },
  heading: {
    color: colors.text.primary,
    fontSize: typography['2xl'],
    fontWeight: '700',
    marginBottom: 4,
  },
  sub: { color: colors.text.muted, fontSize: typography.sm, marginBottom: spacing.lg },
  dayCard: {
    backgroundColor: colors.bg.secondary,
    borderRadius: 16,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayLabel: {
    color: colors.brand.secondary,
    fontSize: typography.lg,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  exRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  exName: { color: colors.text.primary, fontSize: typography.sm },
  exMeta: { color: colors.text.muted, fontSize: typography.sm },
  btn: {
    backgroundColor: colors.brand.primary,
    borderRadius: 12,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  btnOff: { opacity: 0.5 },
  btnText: { color: '#fff', fontSize: typography.base, fontWeight: '700' },
  regenBtn: {
    borderRadius: 12,
    paddingVertical: spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  regenBtnText: { color: colors.text.secondary, fontSize: typography.base, fontWeight: '600' },
  errorText: {
    color: colors.error,
    fontSize: typography.base,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
});
